# Site settings
title: Homepage
description: Erald David Link Blog

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Navigation structure
nav:
  - title: About Me
    url: /about
  - title: Essays
    url: /essays
  - title: Projects
    url: /projects

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- .git
- .github
