# Site settings
title: Homepage
description: Erald David Link Blog

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Navigation
header_pages:
- about_me.md
- essays.md
- projects.md

navigation:
- title: About Me
url: /about_me
- title: Essays
url: /essays
- title: Projects
url: /projects

# Build Settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag

# Exclude from processing
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- .git
- .github
