# Site settings
title: Homepage
description: Erald David link Blog
theme: jekyll-theme-minimal
show_downloads: false

# Navigation structure
nav:
  - title: About Me
    url: /about
  - title: Essays
    url: /essays
  - title: Projects
    url: /projects

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- .git
- .github
